---
- name: make sure to become true
  include: ensure_become.yml

- name: Ensure epel is installed
  yum:
    name: epel-release
    state: installed

- name: ensure fail2ban is installed
  package:
    name: "{{ item }}"
    state: installed
  with_items:
   - fail2ban
   - fail2ban-systemd

- name: ensure SELinux policy management packages are installed
  yum:
    name: selinux-policy*
    state: latest

# TODO: multiples(?)
- name: configure jails
  template:
    src:  "{{ fail2ban_jail_config_template }}"
    dest: "{{ fail2ban_jail_dir }}/{{ fail2ban_app_name }}.conf"
  notify: restart fail2ban

# TODO: multiples(?)
- name: configure filters
  template:
    src:  "{{ fail2ban_filter_config_template }}"
    dest: "{{ fail2ban_filter_dir }}/{{ fail2ban_app_name }}.conf"
  notify: restart fail2ban

- name: ensure fail2ban is enabled and started
  systemd:
    name: fail2ban
    enabled: yes
    state : started
